import { useMemo, useState } from "react";
import { Check, CheckCircle2, ChevronRight, LockKeyhole, ShieldCheck, UserCheck } from "lucide-react";
import type { EvaluationGroup, FlowApplication, Room } from "../../services/api";

export type SpecialtyProfile = "PSYCHOMOTOR" | "PSYCHOLOGY" | "INDICATORS" | "GROUP_OBSERVATION" | "SUPPORT" | "DAP";
type Score = 0 | 1 | 2 | 3 | 4 | "NOT_OBSERVED";
type Screen = "agenda" | "confirm" | "evaluate";

const profiles: Record<SpecialtyProfile, { title: string; instrument: string; description: string; mode: "group" | "individual"; roomIndex: number; derived?: boolean; restricted?: boolean; criteria: string[] }> = {
  PSYCHOMOTOR: { title: "Evaluador de psicomotricidad", instrument: "Psicomotricidad", description: "Coordinación, control motor y ejecución de actividades.", mode: "group", roomIndex: 1, criteria: ["Saltos y equilibrio", "Lanzamiento y coordinación", "Imitación motora", "Control inhibitorio", "Desplazamiento y orientación", "Coordinación bilateral", "Motricidad fina"] },
  PSYCHOLOGY: { title: "Evaluador de psicología", instrument: "Psicología", description: "Adaptación, comunicación, vinculación y motivación.", mode: "individual", roomIndex: 2, restricted: true, criteria: ["Adaptación a la instancia", "Comunicación funcional", "Vinculación con adultos", "Seguimiento de instrucciones", "Motivación y disposición", "Regulación emocional"] },
  INDICATORS: { title: "Evaluador de indicadores de ingreso", instrument: "Indicadores de ingreso", description: "Conductas observables durante el ingreso a la jornada.", mode: "group", roomIndex: 3, criteria: ["Separación del adulto", "Contacto visual", "Disposición inicial", "Respuesta al nombre", "Exploración del espacio", "Regulación durante el ingreso"] },
  GROUP_OBSERVATION: { title: "Evaluador de observación grupal", instrument: "Observación grupal", description: "Participación e interacción dentro del grupo de pares.", mode: "group", roomIndex: 4, criteria: ["Integración al grupo", "Interacción con pares", "Respeto de turnos", "Respuesta a la mediación", "Participación en la actividad", "Resolución de conflictos"] },
  SUPPORT: { title: "Profesional de apoyo al aprendizaje", instrument: "Apoyo al Aprendizaje", description: "Profundización para postulantes derivados durante la jornada.", mode: "individual", roomIndex: 5, derived: true, restricted: true, criteria: ["Lenguaje y comprensión", "Atención y mediación", "Respuesta a apoyos", "Flexibilidad cognitiva", "Necesidad de apoyo"] },
  DAP: { title: "Profesional DAP", instrument: "DAP", description: "Registro especializado y restringido cuando corresponde.", mode: "individual", roomIndex: 6, derived: true, restricted: true, criteria: ["Antecedentes pertinentes", "Adaptación al contexto", "Observación especializada", "Necesidad de profundización", "Recomendación restringida"] },
};

function fullName(app: FlowApplication) { return [app.identity.firstName, app.identity.paternalLastName, app.identity.maternalLastName].filter(Boolean).join(" "); }
function initials(app: FlowApplication) { return `${app.identity.firstName?.[0] ?? ""}${app.identity.paternalLastName?.[0] ?? ""}`; }
function formatTime(iso: string) { return new Intl.DateTimeFormat("es-CL", { hour: "2-digit", minute: "2-digit", hour12: false, timeZone: "America/Santiago" }).format(new Date(iso)); }
const statusLabels: Record<string, string> = { DRAFT: "Pendiente", RECEPTION: "Recepción", CONFIRMED: "Listo", IN_PROGRESS: "En curso", REVIEW: "En revisión", COMPLETED: "Validado" };

export function SpecialtyEvaluatorConsole({ profile, groups, applications, rooms }: { profile: SpecialtyProfile; groups: EvaluationGroup[]; applications: FlowApplication[]; rooms: Room[] }) {
  const config = profiles[profile];
  const room = rooms[config.roomIndex] ?? rooms[0];
  const assignments = useMemo(() => groups.filter((group) => !room || group.roomId === room.roomId).sort((a, b) => a.startsAt.localeCompare(b.startsAt)).slice(0, config.derived ? 3 : 7), [groups, room, config.derived]);
  const [screen, setScreen] = useState<Screen>("agenda");
  const [groupId, setGroupId] = useState(assignments[0]?.groupId ?? "");
  const [criterion, setCriterion] = useState(0);
  const [activeApplicant, setActiveApplicant] = useState("");
  const [responses, setResponses] = useState<Record<string, Record<number, Record<string, Score>>>>({});
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [submitted, setSubmitted] = useState<Record<string, boolean>>({});
  const group = assignments.find((item) => item.groupId === groupId) ?? assignments[0];
  const members = (group?.memberIds.map((id) => applications.find((app) => app.applicationId === id)).filter(Boolean) ?? []) as FlowApplication[];
  const selectedApplicantId = activeApplicant || members[0]?.applicationId || "";
  const current = group ? responses[group.groupId]?.[criterion] ?? {} : {};
  const completed = members.filter((app) => current[app.applicationId] !== undefined).length;
  const chooseGroup = (id: string) => { setGroupId(id); setCriterion(0); setActiveApplicant(""); setScreen("confirm"); };
  const score = (appId: string, value: Score) => { if (!group) return; setResponses((all) => ({ ...all, [group.groupId]: { ...(all[group.groupId] ?? {}), [criterion]: { ...(all[group.groupId]?.[criterion] ?? {}), [appId]: value } } })); };
  const finish = () => { if (!group) return; setSubmitted((all) => ({ ...all, [group.groupId]: true })); setScreen("agenda"); };

  return <div className="space-y-5">
    <div className={`flex flex-wrap items-center justify-between gap-4 rounded-xl border p-4 ${config.restricted ? "border-violet-200 bg-violet-50 text-violet-950" : "border-blue-200 bg-blue-50 text-blue-950"}`}><div className="flex items-center gap-3">{config.restricted ? <LockKeyhole size={20} /> : <UserCheck size={20} />}<div><p className="text-sm font-black">Espacio exclusivo: {config.title}</p><p className="text-xs opacity-80">Solo aparecen las asignaciones y la pauta de esta especialidad.</p></div></div><span className="rounded-lg bg-white px-3 py-2 text-xs font-black">{room?.name ?? "Sala sin asignar"}</span></div>

    {screen === "agenda" && <div><Heading eyebrow="Espacio del evaluador" title={config.derived ? "Mis casos derivados" : "Mi jornada"} text={config.derived ? "Solo aparecen postulantes derivados y autorizados para esta especialidad." : "Revisa los bloques asignados y abre el grupo que corresponde evaluar."} /><div className="space-y-3">{assignments.map((item) => { const people = item.memberIds.map((id) => applications.find((app) => app.applicationId === id)).filter(Boolean) as FlowApplication[]; return <button key={item.groupId} className="grid min-h-20 w-full items-center overflow-hidden rounded-xl border border-slate-200 bg-white text-left shadow-sm hover:border-blue-400 md:grid-cols-[110px_1fr_150px]" onClick={() => chooseGroup(item.groupId)}><time className="border-r border-slate-200 p-4 text-xl font-black">{formatTime(item.startsAt)}<small className="block text-xs text-slate-500">30 min</small></time><span className="min-w-0 p-4"><b className="block text-sm">{item.code} · {item.roomName}</b><small className="mt-1 block truncate text-slate-500">{people.map(fullName).join(" · ")}</small></span><span className="flex items-center justify-end gap-2 p-4"><i className="rounded-full bg-blue-50 px-3 py-1 text-xs font-black not-italic text-blue-800">{submitted[item.groupId] ? "En revisión" : statusLabels[item.status] ?? item.status}</i><ChevronRight size={18} /></span></button>; })}</div></div>}

    {screen === "confirm" && group && <div><Heading eyebrow={`${formatTime(group.startsAt)} · ${group.roomName}`} title="Confirmar grupo" text="Verifica los postulantes antes de abrir la pauta asignada." /><section className="rounded-2xl border border-slate-200 bg-white"><div className="grid gap-4 p-5 md:grid-cols-3">{members.map((app, index) => <article key={app.applicationId} className="relative rounded-xl border border-slate-200 p-5 text-center"><span className="absolute left-3 top-3 grid h-6 w-6 place-items-center rounded bg-slate-100 text-xs font-black">{index + 1}</span><span className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-blue-50 font-black text-blue-900">{initials(app)}</span><h3 className="mt-3 text-sm font-black">{fullName(app)}</h3><p className="mt-1 text-xs text-slate-500">{app.identity.rut}</p><p className="mt-3 text-xs font-bold text-emerald-700"><Check className="mr-1 inline" size={14} />Identidad confirmada</p></article>)}</div><div className="flex justify-end gap-2 border-t border-slate-200 p-5"><button className="secondary" onClick={() => setScreen("agenda")}>Volver</button><button className="primary" onClick={() => setScreen("evaluate")}>Comenzar {config.mode === "group" ? "evaluación simultánea" : "evaluación individual"} <ChevronRight className="ml-1 inline" size={17} /></button></div></section></div>}

    {screen === "evaluate" && group && (config.mode === "group" ? <GroupEvaluation config={config} group={group} members={members} criterion={criterion} current={current} completed={completed} onScore={score} onPrevious={() => setCriterion((value) => value - 1)} onNext={() => setCriterion((value) => value + 1)} onFinish={finish} /> : <IndividualEvaluation config={config} group={group} members={members} selectedId={selectedApplicantId} criterion={criterion} current={current} notes={notes} onSelect={setActiveApplicant} onScore={score} onNote={(id, note) => setNotes((all) => ({ ...all, [id]: note }))} onPrevious={() => setCriterion((value) => value - 1)} onNext={() => setCriterion((value) => value + 1)} onFinish={finish} />)}
  </div>;
}

function Heading({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div className="mb-5"><p className="text-xs font-black uppercase tracking-[0.14em] text-blue-700">{eyebrow}</p><h2 className="mt-1 text-3xl font-black text-slate-950">{title}</h2><p className="mt-1 text-sm text-slate-600">{text}</p></div>; }
const scoreOptions: Array<{ value: Score; title: string; label: string }> = [{ value: 0, title: "0", label: "No logrado" }, { value: 1, title: "1", label: "En proceso" }, { value: 2, title: "2", label: "En proceso" }, { value: 3, title: "3", label: "En proceso" }, { value: 4, title: "4", label: "Logrado" }, { value: "NOT_OBSERVED", title: "—", label: "No observado" }];
function ScorePicker({ value, onChange }: { value?: Score; onChange: (value: Score) => void }) { return <div className="grid grid-cols-2 gap-2">{scoreOptions.map((option) => <button key={String(option.value)} className={`min-h-16 rounded-lg border p-2 ${value === option.value ? "border-2 border-blue-700 bg-blue-50" : "border-slate-200 hover:border-blue-300"}`} onClick={() => onChange(option.value)}><b className="block text-lg">{option.title}</b><small className="text-slate-500">{option.label}</small></button>)}</div>; }

function GroupEvaluation({ config, group, members, criterion, current, completed, onScore, onPrevious, onNext, onFinish }: any) { return <div><div className="mb-5 flex items-end justify-between"><Heading eyebrow={`${formatTime(group.startsAt)} · ${group.roomName} · ${group.code}`} title={`Evaluación de ${config.instrument.toLowerCase()}`} text="Un criterio a la vez, con los tres postulantes visibles en paralelo." /><span className="rounded-xl bg-blue-50 px-4 py-3 text-sm font-black text-blue-900">Criterio {criterion + 1} de {config.criteria.length}</span></div><section className="rounded-2xl border border-slate-200 bg-white"><div className="flex items-center gap-4 border-b border-slate-200 p-5"><span className="grid h-14 w-14 place-items-center rounded-xl bg-blue-900 text-xl font-black text-white">{criterion + 1}</span><div className="flex-1"><p className="text-xs text-slate-500">Pauta observable</p><h3 className="text-xl font-black">{config.criteria[criterion]}</h3><p className="text-sm text-slate-600">Selecciona el nivel observado. “No observado” no equivale a cero.</p></div><strong className={completed === members.length ? "text-emerald-700" : "text-slate-500"}>{completed}/{members.length} completos</strong></div><div className="grid gap-4 p-5 xl:grid-cols-3">{members.map((app: FlowApplication) => <article key={app.applicationId} className="rounded-xl border border-slate-200 p-4"><div className="mb-4 flex items-center gap-3 border-b border-slate-200 pb-4"><span className="grid h-11 w-11 place-items-center rounded-full bg-blue-50 font-black text-blue-900">{initials(app)}</span><div><h4 className="font-black">{fullName(app)}</h4><p className="text-xs text-slate-500">{app.identity.rut}</p></div></div><ScorePicker value={current[app.applicationId]} onChange={(value) => onScore(app.applicationId, value)} /></article>)}</div><Footer criterion={criterion} count={config.criteria.length} canContinue={completed === members.length} onPrevious={onPrevious} onNext={onNext} onFinish={onFinish} /></section></div>; }

function IndividualEvaluation({ config, group, members, selectedId, criterion, current, notes, onSelect, onScore, onNote, onPrevious, onNext, onFinish }: any) { const app = members.find((item: FlowApplication) => item.applicationId === selectedId) ?? members[0]; return <div><Heading eyebrow={`${formatTime(group.startsAt)} · ${group.roomName} · Acceso restringido`} title={`Evaluación individual · ${config.instrument}`} text="Registra únicamente evidencia observable y pertinente para esta especialidad." /><div className="grid gap-5 xl:grid-cols-[270px_1fr]"><aside className="h-fit rounded-2xl border border-slate-200 bg-white p-3"><h3 className="px-3 py-2 font-black">Postulantes asignados</h3>{members.map((person: FlowApplication) => <button key={person.applicationId} onClick={() => onSelect(person.applicationId)} className={`mb-1 flex w-full items-center gap-3 rounded-lg p-3 text-left ${person.applicationId === app?.applicationId ? "bg-blue-50 text-blue-900" : "hover:bg-slate-50"}`}><span className="grid h-9 w-9 place-items-center rounded-full bg-white text-xs font-black">{initials(person)}</span><span className="min-w-0 flex-1"><b className="block truncate text-sm">{fullName(person)}</b><small>{person.identity.rut}</small></span><ChevronRight size={16} /></button>)}</aside>{app && <section className="rounded-2xl border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><div className="flex items-start justify-between"><div><p className="text-xs text-slate-500">Criterio {criterion + 1} de {config.criteria.length}</p><h3 className="text-xl font-black">{config.criteria[criterion]}</h3><p className="mt-1 text-sm text-slate-600">Postulante: {fullName(app)}</p></div><span className="rounded-lg bg-violet-50 p-2 text-violet-800"><LockKeyhole size={20} /></span></div></div><div className="p-5"><ScorePicker value={current[app.applicationId]} onChange={(value) => onScore(app.applicationId, value)} /><label className="mt-5 block text-sm font-bold text-slate-700">Observación profesional<textarea className="control mt-1 min-h-28 w-full py-3" value={notes[app.applicationId] ?? ""} onChange={(event) => onNote(app.applicationId, event.target.value)} placeholder="Evidencia observable, contexto y mediaciones realizadas…" /></label><div className="mt-4 flex items-center gap-2 rounded-lg bg-violet-50 p-3 text-xs font-semibold text-violet-900"><ShieldCheck size={17} />Esta observación no aparece en vistas operativas generales.</div></div><Footer criterion={criterion} count={config.criteria.length} canContinue={current[app.applicationId] !== undefined} onPrevious={onPrevious} onNext={onNext} onFinish={onFinish} /></section>}</div></div>; }

function Footer({ criterion, count, canContinue, onPrevious, onNext, onFinish }: { criterion: number; count: number; canContinue: boolean; onPrevious: () => void; onNext: () => void; onFinish: () => void }) { return <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 p-5"><button className="secondary" disabled={criterion === 0} onClick={onPrevious}>Anterior</button><span className="text-sm font-semibold text-slate-500"><Check className="mr-1 inline text-emerald-600" size={16} />Guardado automático local</span>{criterion < count - 1 ? <button className="primary" disabled={!canContinue} onClick={onNext}>Siguiente criterio <ChevronRight className="ml-1 inline" size={17} /></button> : <button className="primary" disabled={!canContinue} onClick={onFinish}><CheckCircle2 className="mr-2 inline" size={17} />Enviar a revisión</button>}</div>; }
