export type SpecialtyProfile =
  | "ACADEMIC"
  | "PSYCHOMOTOR"
  | "PSYCHOLOGY"
  | "INDICATORS"
  | "GROUP_OBSERVATION"
  | "LEARNING_SUPPORT"
  | "DAP";

export const PROFILE_LABELS: Record<SpecialtyProfile, string> = {
  ACADEMIC: "Evaluador Académico",
  PSYCHOMOTOR: "Psicomotricidad",
  PSYCHOLOGY: "Psicología",
  INDICATORS: "Indicadores de Ingreso",
  GROUP_OBSERVATION: "Observación Grupal",
  LEARNING_SUPPORT: "Apoyo al Aprendizaje",
  DAP: "DAP",
};

export const PROFILE_ROLES: Record<SpecialtyProfile, string> = {
  ACADEMIC: "PK_EVALUATOR_ACADEMIC",
  PSYCHOMOTOR: "PK_EVALUATOR_PSYCHOMOTOR",
  PSYCHOLOGY: "PK_EVALUATOR_PSYCHOLOGY",
  INDICATORS: "PK_EVALUATOR_ENTRY_INDICATORS",
  GROUP_OBSERVATION: "PK_EVALUATOR_GROUP_OBSERVATION",
  LEARNING_SUPPORT: "PK_EVALUATOR_LEARNING_SUPPORT",
  DAP: "PK_EVALUATOR_DAP",
};

export const INSTRUMENT_TO_PROFILE: Record<string, SpecialtyProfile> = {
  // Full codes (from backend API)
  PK_EVALUATOR_ACADEMIC: "ACADEMIC",
  PK_EVALUATOR_PSYCHOMOTOR: "PSYCHOMOTOR",
  PK_EVALUATOR_PSYCHOLOGY: "PSYCHOLOGY",
  PK_EVALUATOR_ENTRY_INDICATORS: "INDICATORS",
  PK_EVALUATOR_GROUP_OBSERVATION: "GROUP_OBSERVATION",
  PK_EVALUATOR_LEARNING_SUPPORT: "LEARNING_SUPPORT",
  PK_EVALUATOR_DAP: "DAP",
  // Short codes (from workspace API)
  ACADEMIC: "ACADEMIC",
  PSYCHOMOTOR: "PSYCHOMOTOR",
  PSYCHOLOGY: "PSYCHOLOGY",
  ENTRY_INDICATORS: "INDICATORS",
  GROUP_OBSERVATION: "GROUP_OBSERVATION",
  LEARNING_SUPPORT: "LEARNING_SUPPORT",
  DAP: "DAP",
};

export const PROFILE_TO_INSTRUMENT: Record<SpecialtyProfile, string> = {
  ACADEMIC: "PK_EVALUATOR_ACADEMIC",
  PSYCHOMOTOR: "PK_EVALUATOR_PSYCHOMOTOR",
  PSYCHOLOGY: "PK_EVALUATOR_PSYCHOLOGY",
  INDICATORS: "PK_EVALUATOR_ENTRY_INDICATORS",
  GROUP_OBSERVATION: "PK_EVALUATOR_GROUP_OBSERVATION",
  LEARNING_SUPPORT: "PK_EVALUATOR_LEARNING_SUPPORT",
  DAP: "PK_EVALUATOR_DAP",
};

// Short codes returned by the workspace API (used for comparison)
export const PROFILE_TO_SHORT_INSTRUMENT: Record<SpecialtyProfile, string> = {
  ACADEMIC: "ACADEMIC",
  PSYCHOMOTOR: "PSYCHOMOTOR",
  PSYCHOLOGY: "PSYCHOLOGY",
  INDICATORS: "ENTRY_INDICATORS",
  GROUP_OBSERVATION: "GROUP_OBSERVATION",
  LEARNING_SUPPORT: "LEARNING_SUPPORT",
  DAP: "DAP",
};
